server:
  port: 8001 #服务端口

#spring相关配置
spring:
  application:
    name: mcroservice-payment  #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3306/springclouddemo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root

  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        # 采样率值介于0到1之间，1表示全部采集
        probability: 1

#mybatis配置
mybatis:
  mapperLocations: classpath:dao/*.xml
  type-aliases-package: com.pccw.springcloud.pojo    # 所有pojo别名类所在包

#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机配置,集群配置可配多个
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
